version: "3.8"
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=scrapr

  pgadmin:
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=name@example.com
        - PGADMIN_DEFAULT_PASSWORD=admin
      ports:
        - '5050:80'
      restart:
        always
