default:
  name: 'Dev'
  response: 'not-found 404'
  db:
    engine: 'postgresql'
  secret_key: settings.get('secret_key')
  SECURITY_PASSWORD_SALT: settings.get('SECURITY_PASSWORD_SALT')
  DB_NAME: 'scrape'
  DB_URI: 'postgresql+psycopg2://root:root@localhost:5432/scrape'
  host: 'localhost'
  user: 'root'